version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            sudo python setup.py install
            pip wheel cryptography
            ls -l
            doctor-wheel *.whl
            ls -l
            pip install *.whl
          name: Install and test

workflows:
  main:
    jobs:
      - build-and-test
